name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Neo4j Cypher-DSL
    runs-on: ubuntu-latest
    outputs:
          revision: ${{ steps.revision_step.outputs.revision }}
          output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: Enable Sonar for local PRs not from Dependabot
        if:  ${{ github.event.sender.login != 'dependabot[bot]' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}
        run: echo "USE_SONAR=sonar" >> $GITHUB_ENV
      - name: Disable Sonar for foreign PRs or from Dependabot
        if:  ${{ github.event.sender.login == 'dependabot[bot]' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) }}
        run: echo "USE_SONAR=-sonar" >> $GITHUB_ENV
      - name: Determine revision
        id: revision_step
        run: |
          REVISION=foo
          echo "REVISION=$REVISION" >> $GITHUB_ENV
          echo "::set-output name=revision::$REVISION"

  test_on_jdk8:
    name: Verify tests on JDK 8
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Determine revision
        run: echo "REVISION=${{ needs.build.outputs.revision }}" >> $GITHUB_ENV
